// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4eQbxHCUXL3hgEpU1oCZ2venhrz6YErU',
    appId: '1:278325668737:web:13cde032200d64e2f29680',
    messagingSenderId: '278325668737',
    projectId: 'unflash-be2ec',
    authDomain: 'unflash-be2ec.firebaseapp.com',
    storageBucket: 'unflash-be2ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA30UbECAzg-CpfrbNyWdqHIJiZHlWRJJ0',
    appId: '1:278325668737:android:e16ad520a66bb7fdf29680',
    messagingSenderId: '278325668737',
    projectId: 'unflash-be2ec',
    storageBucket: 'unflash-be2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqAFklDAxVZI4vunjqJOyQmtBPnx7WreM',
    appId: '1:278325668737:ios:ba9a97b5b029b41df29680',
    messagingSenderId: '278325668737',
    projectId: 'unflash-be2ec',
    storageBucket: 'unflash-be2ec.appspot.com',
    iosClientId:
        '278325668737-4lotk2aapn1bmjac3rdn301v409cev61.apps.googleusercontent.com',
    iosBundleId: 'com.example.harvesthacks2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqAFklDAxVZI4vunjqJOyQmtBPnx7WreM',
    appId: '1:278325668737:ios:ba9a97b5b029b41df29680',
    messagingSenderId: '278325668737',
    projectId: 'unflash-be2ec',
    storageBucket: 'unflash-be2ec.appspot.com',
    iosClientId:
        '278325668737-4lotk2aapn1bmjac3rdn301v409cev61.apps.googleusercontent.com',
    iosBundleId: 'com.example.harvesthacks2022',
  );

  static const token = "sussyamogusimposter18828828877yy8dbjsdjkf!***((**";
}
